### PR TITLE
Version bumps

### PR DESCRIPTION
**Pull request by BardurArantsson**
The commits should be self-explanatory

### CODE REVIEW

**Comment by BardurArantsson** [comment]
Btw, assuming the travis checks go through, it would be realy nice to get a new release of argonaut-unfiltered as well :).

**Comment by BardurArantsson** [comment]
Yay. *Finally* got the travis build to pass.

**Comment by BardurArantsson** [comment]
@markhibberd Ping?

**Comment by markhibberd** [comment]
@BardurArantsson Can you just take over maintaining this library? I can add you to repository.

**Comment by BardurArantsson** [comment]
I'm not sure about taking over, but I'd be happy to share custody :). I'm not sure how to do releases, though. Perhaps you can offer some guidance?

**Comment by BardurArantsson** [comment]
Ping :)

**Comment by BardurArantsson** [comment]
Ping?

I'm still quite willing to do a release...

**Comment by markhibberd** [comment]
@BardurArantsson Sorry, but I don't open-source any more, especially scala open-source, if someone else isn't willing to take it over (I am more than happy to assign it to anyone who wants to look after it) then there isn't much that can be done.

**Comment by seanparsons** [comment]
Ah, sorry, this is my fault, it came to my attention while I was at work. I'll have a think about this at the weekend.

**Comment by BardurArantsson** [comment]
@markhibberd Ah, sorry to hear it... or happy if you're happier as a result :). Dependency handling in Scala is turning out to be... a challenge. (Even more so with the "killer app" of Scala.js.)

@seanparsons No problem -- in the end it's, what, 10-15 lines of code, so it's not a disaster to just Copy/Paste it if need be. (Or maybe just do a fork and publish that.)

**Pull request merged**
